###간단한 DF

In [6]:
import pandas as pd
import numpy

customers = pd.DataFrame({
    "customer_id" : [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]})

orders = pd.DataFrame({
    "order_id" : [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 5],
    "amount" : [30000, 12000, 45000, 9999]})

customers, orders

(   customer_id name
 0            1    A
 1            2    B
 2            3    C
 3            4    D,
    order_id  customer_id  amount
 0       101            1   30000
 1       102            1   12000
 2       103            2   45000
 3       104            5    9999)

###INNER JOIN : 양쪽에 모두 있는 행만 합치기

In [7]:
inner = pd.merge(customers, orders, on="customer_id", how="inner")
inner

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000

###LEFT JOIN : 왼쪽 전부 살리기

In [8]:
left = pd.merge(customers, orders, on="customer_id", how="left")
left

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN

In [9]:
left_only = left[left["order_id"].isnull()]
left_only

   customer_id name  order_id  amount
3            3    C       NaN     NaN
4            4    D       NaN     NaN

###RIGHT JOIN : 오른쪽 전부 살리기

In [10]:
right = pd.merge(customers, orders, on="customer_id", how="right", indicator=True)
right

   customer_id name  order_id  amount      _merge
0            1    A       101   30000        both
1            1    A       102   12000        both
2            2    B       103   45000        both
3            5  NaN       104    9999  right_only

In [11]:
right_only = right[right["name"].isnull()]
right_only

   customer_id name  order_id  amount      _merge
3            5  NaN       104    9999  right_only

###FULL OUTER JOIN : 양쪽 모든 행 합치기

In [12]:
outer = pd.merge(customers, orders, on="customer_id", how="outer", indicator=True)
outer

   customer_id name  order_id   amount      _merge
0            1    A     101.0  30000.0        both
1            1    A     102.0  12000.0        both
2            2    B     103.0  45000.0        both
3            3    C       NaN      NaN   left_only
4            4    D       NaN      NaN   left_only
5            5  NaN     104.0   9999.0  right_only

###CONCAT

In [13]:
concat = pd.concat([customers, orders])
concat

   customer_id name  order_id   amount
0            1    A       NaN      NaN
1            2    B       NaN      NaN
2            3    C       NaN      NaN
3            4    D       NaN      NaN
0            1  NaN     101.0  30000.0
1            1  NaN     102.0  12000.0
2            2  NaN     103.0  45000.0
3            5  NaN     104.0   9999.0

In [14]:
concat = pd.concat([customers, orders], axis = 1)
concat

   customer_id name  order_id  customer_id  amount
0            1    A       101            1   30000
1            2    B       102            1   12000
2            3    C       103            2   45000
3            4    D       104            5    9999

###Olist data join

In [20]:
import pandas as pd

#파일 불러오기
customers = pd.read_csv("olist_customers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
product_category = pd.read_csv("product_category_name_translation.csv")

#조인하기
merged_df = customers.merge(orders, on='customer_id', how='left')
merged_df = merged_df.merge(order_items, on='order_id', how='left')
merged_df = merged_df.merge(products, on='product_id', how='left')
merged_df = merged_df.merge(sellers, on='seller_id', how='left')
merged_df = merged_df.merge(product_category, on='product_category_name', how='left')
merged_df = merged_df.merge(order_payments, on='order_id', how='left')
merged_df = merged_df.merge(order_reviews, on='order_id', how='left')

display(merged_df)
print(merged_df.columns)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1.0,credit_card,2.0,146.87,88b8b52d46df026a9d1ad2136a59b30b,4.0,NaN,NaN,2017-05-26 00:00:00,2017-05-30 22:34:40
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,1.0,credit_card,8.0,335.48,02fc48a9efa3e3d0f1a8ea26507eeec3,5.0,NaN,NaN,2018-01-30 00:00:00,2018-02-10 22:43:29
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,1.0,credit_card,7.0,157.73,5ad6695d76ee186dc473c42706984d87,5.0,NaN,NaN,2018-06-15 00:00:00,2018-06-15 12:10:59
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,1.0,credit_card,1.0,173.30,059a801bb31f6aab2266e672cab87bc5,5.0,NaN,NaN,2018-03-29 00:00:00,2018-04-02 18:36:47
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,1.0,credit_card,8.0,252.25,8490879d58d6c5d7773f2739a03f089a,5.0,a melhor nota,O baratheon è esxelente Amo adoro o baratheon,2018-08-10 00:00:00,2018-08-17 01:59:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,1.0,credit_card,6.0,88.78,36e2cdbaa9f639b57c53b37ac798fee8,4.0,Recomendo,NaN,2018-04-14 00:00:00,2018-04-28 11:15:04
119139,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,1.0,credit_card,3.0,129.06,b273b431c3aedb4eed18643309652940,5.0,NaN,NaN,2018-04-12 00:00:00,2018-04-16 10:36:05
119140,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,1.0,credit_card,5.0,56.04,fa4f16891e6b2edd1354668d07f5648b,1.0,Chateada,Esperava qualidade no atendimento e estou tend...,2018-05-04 00:00:00,2018-05-08 01:41:07
119141,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,1.0,credit_card,2.0,711.07,0bcdc9e450ea500811a8d39ee993cd47,5.0,NaN,NaN,2017-11-17 00:00:00,2017-11-19 23:34:18
119142,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,...,1.0,credit_card,1.0,21.77,d95d701d062d2bb88041768a63aa750d,5.0,NaN,"Produto chegou bem antes do prazo , gostei mui...",2017-12-27 00:00:00,2017-12-27 23:21:06

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'review_id', 'review_score',
       'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp'],
      dtype='str')